joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

j2n6s300_joint_1_controller:
  type: effort_controllers/JointPositionController
  joint: j2n6s300_joint_1
  pid: {p: 500.0, i: 4.0, d: 10.0, i_clmap_min: -100.0, i_clamp_max: 100.0}

j2n6s300_joint_2_controller:
  type: effort_controllers/JointPositionController
  joint: j2n6s300_joint_2
  pid: {p: 220.0, i: 0.0, d: 20.0, i_clmap_min: -200.0, i_clamp_max: 200.0}
  
j2n6s300_joint_3_controller:
  type: effort_controllers/JointPositionController
  joint: j2n6s300_joint_3
  pid: {p: 500.0, i: 0.0, d: 10.0, i_clmap_min: -200.0, i_clamp_max: 200.0}

j2n6s300_joint_4_controller:
  type: effort_controllers/JointPositionController
  joint: j2n6s300_joint_4
  pid: {p: 100.0, i: 1.0, d: 0.1, i_clmap_min: -100.0, i_clamp_max: 100.0}

j2n6s300_joint_5_controller:
  type: effort_controllers/JointPositionController
  joint: j2n6s300_joint_5
  pid: {p: 400.0, i: 4.0, d: 1.0, i_clmap_min: -100.0, i_clamp_max: 100.0}

j2n6s300_joint_6_controller:
  type: effort_controllers/JointPositionController
  joint: j2n6s300_joint_6
  pid: {p: 100.0, i: 1.0, d: 0.1, i_clmap_min: -100.0, i_clamp_max: 100.0}

j2n6s300_joint_finger_1_controller:
  type: effort_controllers/JointPositionController
  joint: j2n6s300_joint_finger_1
  pid: {p: 1.0, i: 2.0, d: 0.0, i_clmap_min: -100.0, i_clamp_max: 100.0}

j2n6s300_joint_finger_2_controller:
  type: effort_controllers/JointPositionController
  joint: j2n6s300_joint_finger_2
  pid: {p: 1.0, i: 2.0, d: 0.0, i_clmap_min: -100.0, i_clamp_max: 100.0}

j2n6s300_joint_finger_3_controller:
  type: effort_controllers/JointPositionController
  joint: j2n6s300_joint_finger_3
  pid: {p: 1.0, i: 2.0, d: 0.0, i_clmap_min: -100.0, i_clamp_max: 100.0}

j2n6s300_joint_finger_tip_1_controller:
  type: effort_controllers/JointPositionController
  joint: j2n6s300_joint_finger_tip_1
  pid: {p: 0.1, i: 1.0, d: 0.0, i_clmap_min: -100.0, i_clamp_max: 100.0}

j2n6s300_joint_finger_tip_2_controller:
  type: effort_controllers/JointPositionController
  joint: j2n6s300_joint_finger_tip_2
  pid: {p: 0.10, i: 1.0, d: 0.0, i_clmap_min: -100.0, i_clamp_max: 100.0}

j2n6s300_joint_finger_tip_3_controller:
  type: effort_controllers/JointPositionController
  joint: j2n6s300_joint_finger_tip_3
  pid: {p: 0.10, i: 1.0, d: 0.0, i_clmap_min: -100.0, i_clamp_max: 100.0}