controller_list:
  - name: fake_arm_kinova_mico_controller
    type: $(arg fake_execution_type)
    joints:
      - m1n6s300_joint_1
      - m1n6s300_joint_2
      - m1n6s300_joint_3
      - m1n6s300_joint_4
      - m1n6s300_joint_5
      - m1n6s300_joint_6
  - name: fake_gripper_kinova_mico_controller
    type: $(arg fake_execution_type)
    joints:
      - m1n6s300_joint_finger_1
      - m1n6s300_joint_finger_tip_1
      - m1n6s300_joint_finger_2
      - m1n6s300_joint_finger_tip_2
      - m1n6s300_joint_finger_3
      - m1n6s300_joint_finger_tip_3
initial:  # Define initial robot poses per group
  - group: arm_kinova_mico
    pose: ready