arm_kinova_controller_mico:
  type: effort_controllers/JointTrajectoryController
  joints:
    - m1n6s300_joint_1
    - m1n6s300_joint_2
    - m1n6s300_joint_3
    - m1n6s300_joint_4
    - m1n6s300_joint_5
    - m1n6s300_joint_6
  gains:
    m1n6s300_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m1n6s300_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m1n6s300_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m1n6s300_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m1n6s300_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m1n6s300_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_kinova_controller_mico:
  type: effort_controllers/JointTrajectoryController
  joints:
    - m1n6s300_joint_finger_1
    - m1n6s300_joint_finger_tip_1
    - m1n6s300_joint_finger_2
    - m1n6s300_joint_finger_tip_2
    - m1n6s300_joint_finger_3
    - m1n6s300_joint_finger_tip_3
  gains:
    m1n6s300_joint_finger_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m1n6s300_joint_finger_tip_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m1n6s300_joint_finger_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m1n6s300_joint_finger_tip_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m1n6s300_joint_finger_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m1n6s300_joint_finger_tip_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1