controller_list:
  - name: arm_kinova_controller_mico
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - m1n6s300_joint_1
      - m1n6s300_joint_2
      - m1n6s300_joint_3
      - m1n6s300_joint_4
      - m1n6s300_joint_5
      - m1n6s300_joint_6
  - name: gripper_kinova_controller_mico
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - m1n6s300_joint_finger_1
      - m1n6s300_joint_finger_tip_1
      - m1n6s300_joint_finger_2
      - m1n6s300_joint_finger_tip_2
      - m1n6s300_joint_finger_3
      - m1n6s300_joint_finger_tip_3