controller_list:
  - name: fake_arm_kinvoa_controller
    type: $(arg fake_execution_type)
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
      - j2n6s300_joint_6
  - name: fake_gripper_kinova_controller
    type: $(arg fake_execution_type)
    joints:
      - j2n6s300_joint_finger_1
      - j2n6s300_joint_finger_tip_1
      - j2n6s300_joint_finger_2
      - j2n6s300_joint_finger_tip_2
      - j2n6s300_joint_finger_3
      - j2n6s300_joint_finger_tip_3
initial:  # Define initial robot poses per group
  - group: arm_kinvoa
    pose: zeros
  - group: gripper_kinova
    pose: close