arm_kinvoa_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j2n6s300_joint_1
    - j2n6s300_joint_2
    - j2n6s300_joint_3
    - j2n6s300_joint_4
    - j2n6s300_joint_5
    - j2n6s300_joint_6
  gains:
    j2n6s300_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2n6s300_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2n6s300_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2n6s300_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2n6s300_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2n6s300_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1